clearvars; close all; clc;
run('Library/controllers/setup_simulation_params.m');
MWS = struct();
MWS.engName = 'AGTF30';
MWS = setup_Controller(MWS);
MWS = setup_AllEng(MWS);
MWS.In.Ts = Ts; MWS.In.Tsim = 10;
MWS.In.Alt = timeseries([0;0],[0 10],'Name','Alt');
MWS.In.MN  = timeseries([0;0],[0 10],'Name','MN');
MWS.In.dT  = timeseries([0;0],[0 10],'Name','dT');
MWS.In.dVBV = timeseries([0;0],[0 10],'Name','dVBV');
MWS.In.dNz  = timeseries([0;0],[0 10],'Name','dNz');
MWS.In.Wf   = timeseries([0.5;0.5],[0 10],'Name','Wf');
simIn = Simulink.SimulationInput(MWS.engName);
simIn = simIn.setVariable('MWS',MWS);
simOut = sim(simIn);
out_dyn = fetch_out_dyn(simOut);
N_H = measure_tracking_series(out_dyn, 'N_H');
fprintf('N_H at end of 10s: %.2f\n', N_H(end));
fprintf('N_H from lookup table: %.2f\n', offset.z(idx_NH, k_idle));
